name: enum_type_to_value_list
description: enum type to value list.
version: 0.0.2
homepage: https://github.com/Atsumi3/EnumTypeToValueList

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test:
